import type { Locale } from "@/lib/i18n";

const secondaryCopy = {
  en: {
    fitting: {
      metadataTitle: "3D clothing preview — Weft",
      metadataDescription: "Explore an approximate garment shape on an adjustable 3D mannequin.",
      title: "3D clothing preview",
      lead: "Adjust the mannequin, choose an item, and inspect its approximate shape from every side.",
      photoTitle: "Add a photo",
      photoLead: "Optional. A photo is used only to estimate the mannequin’s skin tone.",
      choosePhoto: "Choose a photo",
      fileTypes: "JPG, PNG or WEBP, up to 10 MB",
      uploadedPhoto: "Your selected photo",
      removePhoto: "Remove photo",
      replacePhoto: "Replace photo",
      invalidType: "Choose a JPG, PNG, or WEBP file.",
      tooLarge: "Choose a photo smaller than 10 MB.",
      localTitle: "Stays on this device",
      localLead: "The photo is processed in this browser and is not sent to a server.",
      measurementsTitle: "Adjust measurements",
      measurementsLead: "Measurements in centimetres change the proportions of the 3D mannequin.",
      height: "Height (cm)", chest: "Chest (cm)", waist: "Waist (cm)", hips: "Hips (cm)",
      shoulders: "Shoulders (cm)", inseam: "Inseam (cm)",
      measurementsStored: "Measurements are saved in this browser only.",
      itemTitle: "Choose an item",
      itemLead: "The preview shows one item at a time.",
      clothing: "Clothing for the 3D preview",
      noItems: "No clothing with an image is available for this preview.",
      previewTitle: "Inspect the shape",
      previewLead: "Drag to rotate the mannequin and view the approximate garment form.",
      previewLoading: "Loading the 3D preview",
      disclaimer: "This is an approximate 3D visualization, not a photorealistic try-on or a guarantee of size, fit, drape, or colour.",
    },
    stores: {
      summary: (items: number, categories: number) => `${items} ${items === 1 ? "piece" : "pieces"} in ${categories} ${categories === 1 ? "category" : "categories"}`,
      imageUnavailable: "Image unavailable",
    },
    state: {
      errorTitle: "This page didn’t load.",
      errorLead: "Try again to reload the same page. Your address and search settings will stay in place.",
      retry: "Try again",
      home: "Return home",
      notFoundTitle: "We can’t find this page.",
      notFoundLead: "The address may have changed, or the item may no longer be available.",
      search: "Explore clothing",
      loading: "Loading page",
      loadingLead: "Preparing clothing and search controls.",
      detailLoading: "Loading item details",
    },
  },
  lt: {
    fitting: {
      metadataTitle: "3D drabužių peržiūra — Weft",
      metadataDescription: "Apžiūrėkite apytikslę drabužio formą ant reguliuojamo 3D manekeno.",
      title: "3D drabužių peržiūra",
      lead: "Sureguliuok manekeną, pasirink drabužį ir apžiūrėk jo apytikslę formą iš visų pusių.",
      photoTitle: "Pridėk nuotrauką",
      photoLead: "Nebūtina. Nuotrauka naudojama tik manekeno odos atspalviui apytiksliai nustatyti.",
      choosePhoto: "Pasirinkti nuotrauką",
      fileTypes: "JPG, PNG arba WEBP, iki 10 MB",
      uploadedPhoto: "Tavo pasirinkta nuotrauka",
      removePhoto: "Pašalinti nuotrauką",
      replacePhoto: "Pakeisti nuotrauką",
      invalidType: "Pasirink JPG, PNG arba WEBP failą.",
      tooLarge: "Pasirink mažesnę nei 10 MB nuotrauką.",
      localTitle: "Lieka šiame įrenginyje",
      localLead: "Nuotrauka apdorojama šioje naršyklėje ir nėra siunčiama į serverį.",
      measurementsTitle: "Sureguliuok išmatavimus",
      measurementsLead: "Išmatavimai centimetrais keičia 3D manekeno proporcijas.",
      height: "Ūgis (cm)", chest: "Krūtinė (cm)", waist: "Liemuo (cm)", hips: "Klubai (cm)",
      shoulders: "Pečiai (cm)", inseam: "Vidinė kojos siūlė (cm)",
      measurementsStored: "Išmatavimai saugomi tik šioje naršyklėje.",
      itemTitle: "Pasirink drabužį",
      itemLead: "Vienu metu peržiūroje rodomas vienas drabužis.",
      clothing: "Drabužiai 3D peržiūrai",
      noItems: "Šiai peržiūrai nėra drabužių su nuotraukomis.",
      previewTitle: "Apžiūrėk formą",
      previewLead: "Vilk ir pasuk manekeną, kad apžiūrėtum apytikslę drabužio formą.",
      previewLoading: "Įkeliama 3D peržiūra",
      disclaimer: "Tai apytikslė 3D vizualizacija, o ne fotorealistinis pasimatavimas ar dydžio, tinkamumo, kritimo arba spalvos garantija.",
    },
    stores: {
      summary: (items: number, categories: number) => `Prekių: ${items} · kategorijų: ${categories}`,
      imageUnavailable: "Nuotrauka nepasiekiama",
    },
    state: {
      errorTitle: "Puslapio įkelti nepavyko.",
      errorLead: "Bandyk dar kartą – bus įkeltas tas pats puslapis, o adresas ir paieškos nustatymai liks nepakitę.",
      retry: "Bandyti dar kartą",
      home: "Grįžti į pradžią",
      notFoundTitle: "Šio puslapio rasti nepavyko.",
      notFoundLead: "Adresas galėjo pasikeisti arba prekė gali būti nebepasiekiama.",
      search: "Naršyti drabužius",
      loading: "Įkeliamas puslapis",
      loadingLead: "Ruošiami drabužiai ir paieškos valdikliai.",
      detailLoading: "Įkeliama prekės informacija",
    },
  },
} as const;

export function getSecondaryCopy(locale: Locale) {
  return secondaryCopy[locale];
}
